"""initial schema

Revision ID: 55ede1e8efab
Revises: 
Create Date: 2026-07-29 00:30:38.486798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '55ede1e8efab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# `users.node_id` y `nodes.leader_id` se referencian mutuamente: la FK de nodes
# se crea con ALTER TABLE una vez que ambas tablas existen.
NODES_LEADER_FK = "fk_nodes_leader_id_users"

# Postgres no elimina los tipos ENUM al borrar las tablas; hay que hacerlo
# explícitamente o el siguiente upgrade falla con "type already exists".
ENUM_TYPES = (
    "nodetype",
    "nodestatus",
    "userrole",
    "userstatus",
    "contenttype",
    "contentstatus",
    "eventtype",
    "eventformat",
    "publicationtype",
    "invitationstatus",
    "socialplatform",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('sociedad_civil', 'cientifico', 'empresarial', 'funcion_publica', 'individual', name='nodetype'), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('alt_places', sa.Text(), nullable=True),
    sa.Column('joined_in', sa.Integer(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('memorandum', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='nodestatus'), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_code'), 'nodes', ['code'], unique=True)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'node_leader', 'member', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='userstatus'), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('postgraduate', sa.String(length=255), nullable=True),
    sa.Column('expertise_area', sa.String(length=255), nullable=True),
    sa.Column('research_work', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(NODES_LEADER_FK, 'nodes', 'users', ['leader_id'], ['id'])
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('event', 'publication', 'book', 'project', 'series', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', name='contentstatus'), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.Enum('event', 'taller', 'clase', 'curso', 'seminario', 'foro', 'conferencia', 'congreso', 'webinar', name='eventtype'), nullable=True),
    sa.Column('event_format', sa.Enum('presencial', 'online', name='eventformat'), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('book_author', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('isbn', sa.String(length=100), nullable=True),
    sa.Column('publication_type', sa.Enum('boletin', 'guia', 'articulo', name='publicationtype'), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('issn', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'node_leader', 'member', name='userrole'), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('node_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('member_code', sa.String(length=50), nullable=False),
    sa.Column('research_line', sa.Text(), nullable=True),
    sa.Column('work_area', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_members_id'), 'node_members', ['id'], unique=False)
    op.create_index(op.f('ix_node_members_member_code'), 'node_members', ['member_code'], unique=True)
    op.create_table('node_social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('linkedin', 'github', 'twitter', 'website', 'facebook', 'instagram', 'youtube', 'research_gate', 'phone', name='socialplatform'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_social_links_id'), 'node_social_links', ['id'], unique=False)
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('linkedin', 'github', 'twitter', 'website', 'facebook', 'instagram', 'youtube', 'research_gate', 'phone', name='socialplatform'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_links_id'), 'social_links', ['id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(NODES_LEADER_FK, 'nodes', type_='foreignkey')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_social_links_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_node_social_links_id'), table_name='node_social_links')
    op.drop_table('node_social_links')
    op.drop_index(op.f('ix_node_members_member_code'), table_name='node_members')
    op.drop_index(op.f('ix_node_members_id'), table_name='node_members')
    op.drop_table('node_members')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_code'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
